name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3 # v3 is the latest stable version

      - name: Setup Node
        uses: actions/setup-node@v3 # Use the latest version of setup-node
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1 # This is still fine, though make sure it's what you want. You could also use `run: npm install` if preferred.

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3 # Updated to v3
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3 # Updated to v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Using the latest version of the gh-pages action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
